<?php

namespace Database\Seeders;

use App\Models\Pengujian;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Pengujiansseeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Pengujian::create(['tipe' => 'verbal','soal' => 'SINONIM CERCA','a' => 'potongan kain','gambara' => '-','b' => 'umpatan','gambarb' => '-','c' => 'sulaman','gambarc' => '-','d' => 'terjatuh','gambard' => '-','jawaban' => 'umpatan','gambar' => '-',]);
        Pengujian::create(['tipe' => 'verbal','soal' => 'SINONIM ABERASI','a' => 'pengikisan','gambara' => '-','b' => 'pemisahan','gambarb' => '-','c' => 'penggerusan','gambarc' => '-','d' => 'penyimpangan','gambard' => '-','jawaban' => 'penyimpangan','gambar' => '-',]);
        Pengujian::create(['tipe' => 'verbal','soal' => 'ANTONIM TETIRAN','a' => 'asli','gambara' => '-','b' => 'amatiran','gambarb' => '-','c' => 'palsu','gambarc' => '-','d' => 'petir','gambard' => '-','jawaban' => 'asli','gambar' => '-',]);
        Pengujian::create(['tipe' => 'verbal','soal' => 'ANTONIM LECO','a' => 'cebol','gambara' => '-','b' => 'mungil','gambarb' => '-','c' => 'kerdil','gambarc' => '-','d' => 'raksasa','gambard' => '-','jawaban' => 'raksasa','gambar' => '-',]);
        Pengujian::create(['tipe' => 'verbal','soal' => 'ANTONIM SAHIH','a' => 'cacat','gambara' => '-','b' => 'benar','gambarb' => '-','c' => 'modern','gambarc' => '-','d' => 'tepat','gambard' => '-','jawaban' => 'cacat','gambar' => '-',]);
        Pengujian::create(['tipe' => 'verbal','soal' => 'JARI : CINCIN =','a' => 'pintu:rumah','gambara' => '-','b' => 'kaki:sepatu','gambarb' => '-','c' => 'tangan:tilang','gambarc' => '-','d' => 'anting:giwang','gambard' => '-','jawaban' => 'kaki:sepatu','gambar' => '-',]);
        Pengujian::create(['tipe' => 'verbal','soal' => 'RATU : MAHKOTA','a' => 'nelayan:sampan','gambara' => '-','b' => 'juara:medali','gambarb' => '-','c' => 'sarjana:toga','gambarc' => '-','d' => 'pegawai:dasi','gambard' => '-','jawaban' => 'sarjana:toga','gambar' => '-',]);
        Pengujian::create(['tipe' => 'verbal','soal' => 'SINONIM LUSTRUM','a' => 'dasawarsa','gambara' => '-','b' => 'listrik','gambarb' => '-','c' => 'segilima','gambarc' => '-','d' => 'pancawarsa','gambard' => '-','jawaban' => 'umpatan','gambar' => '-',]);
        Pengujian::create(['tipe' => 'verbal','soal' => 'SINONIM KENYAL','a' => 'kental','gambara' => '-','b' => 'padat','gambarb' => '-','c' => 'luwes','gambarc' => '-','d' => 'elastis','gambard' => '-','jawaban' => 'elastis','gambar' => '-',]);
        Pengujian::create(['tipe' => 'verbal','soal' => 'Kata manakan yang berbeda dari kelompok kata berikut','a' => 'Birmingham','gambara' => '-','b' => 'Turin','gambarb' => '-','c' => 'Liverpool','gambarc' => '-','d' => 'London','gambard' => '-','jawaban' => 'Turin','gambar' => '-',]);
        Pengujian::create(['tipe' => 'bahasa','soal' => 'Menyampaikan informasi, ide, perasaan dengan cara yang sederhana dan mudah dimengerti','a' => 'ya','gambara' => '-','b' => 'tidak','gambarb' => '-','c' => '-','gambarc' => '-','d' => '-','gambard' => '-','jawaban' => '','gambar' => '-',]);
        Pengujian::create(['tipe' => 'bahasa','soal' => 'Mampu menginterpretasikan sesuatu, termasuk menerjemahkannya ke dalam bahasa lain','a' => 'ya','gambara' => '-','b' => 'tidak','gambarb' => '-','c' => '-','gambarc' => '-','d' => '-','gambard' => '-','jawaban' => '-','gambar' => '-',]);
        Pengujian::create(['tipe' => 'bahasa','soal' => 'Membuat orang lain menjadi bersemangat dan tertarik dengan cerita yang kita ceritakan','a' => 'ya','gambara' => '-','b' => 'tidak','gambarb' => '-','c' => '-','gambarc' => '-','d' => '-','gambard' => '-','jawaban' => '-','gambar' => '-',]);
        Pengujian::create(['tipe' => 'bahasa','soal' => 'mudah mengekspresikan sesuatu dengan mudah melalu ucapan atau tulisan','a' => 'ya','gambara' => '-','b' => 'tidak','gambarb' => '-','c' => '-','gambarc' => '-','d' => '-','gambard' => '-','jawaban' => '-','gambar' => '-',]);
        Pengujian::create(['tipe' => 'bahasa','soal' => 'senang bermain kata, misalnya permainan teka teki silang','a' => 'ya','gambara' => '-','b' => 'tidak','gambarb' => '-','c' => '-','gambarc' => '-','d' => '-','gambard' => '-','jawaban' => '-','gambar' => '-',]);
        Pengujian::create(['tipe' => 'bahasa','soal' => 'bisa berdebat kata-kata dengan baik','a' => 'ya','gambara' => '-','b' => 'tidak','gambarb' => '-','c' => '-','gambarc' => '-','d' => '-','gambard' => '-','jawaban' => '-','gambar' => '-',]);
        Pengujian::create(['tipe' => 'bahasa','soal' => 'suka berbicara ketika ada masalah, menjelaskan solusi, dan bertanya jawab?','a' => 'ya','gambara' => '-','b' => 'tidak','gambarb' => '-','c' => '-','gambarc' => '-','d' => '-','gambard' => '-','jawaban' => '-','gambar' => '-',]);
        Pengujian::create(['tipe' => 'bahasa','soal' => 'secara teratur menambah pembendahaeaan kata dengan belajar kata-kata baru','a' => 'ya','gambara' => '-','b' => 'tidak','gambarb' => '-','c' => '-','gambarc' => '-','d' => '-','gambard' => '-','jawaban' => '-','gambar' => '-',]);
        Pengujian::create(['tipe' => 'bahasa','soal' => 'mempunyai pembendaharaan kata yang luas dan dapat mengungkapkan diri dengan baik dengan menggunakan kata-kata tersebut','a' => 'ya','gambara' => '-','b' => 'tidak','gambarb' => '-','c' => '-','gambarc' => '-','d' => '-','gambard' => '-','jawaban' => '-','gambar' => '-',]);
        Pengujian::create(['tipe' => 'bahasa','soal' => 'mudah mengingat melodi atau lirik dari lagu maupun puisi','a' => 'ya','gambara' => '-','b' => 'tidak','gambarb' => '-','c' => '-','gambarc' => '-','d' => '-','gambard' => '-','jawaban' => '-','gambar' => '-',]);
        Pengujian::create(['tipe' => 'numerik','soal' => 'Tulang manusia di bentuk dari 18% berat total manusia, berapa kilogram berat tulang tersebut jika berat seseorang 75 kg','a' => '13.5','gambara' => '-','b' => '12','gambarb' => '-','c' => '61.5','gambarc' => '-','d' => '63','gambard' => '-','jawaban' => '13.5','gambar' => '-',]);
        Pengujian::create(['tipe' => 'numerik','soal' => 'Jika x+y+z = 18 dan y x z = y² + y, berapakah (x+2y)/2?','a' => '8.5','gambara' => '-','b' => '9.5','gambarb' => '-','c' => '10','gambarc' => '-','d' => '11','gambard' => '-','jawaban' => '8.5','gambar' => '-',]);
        Pengujian::create(['tipe' => 'numerik','soal' => '5, 8, 13, 21, 34, 55, 89, 144, …','a' => '203','gambara' => '-','b' => '213','gambarb' => '-','c' => '223','gambarc' => '-','d' => '233','gambard' => '-','jawaban' => '233','gambar' => '-',]);
        Pengujian::create(['tipe' => 'numerik','soal' => '6, 11, 21, …, 81, 9, 14, 24, 44, …','a' => '31 dan 64','gambara' => '-','b' => '36 dan 74','gambarb' => '-','c' => '41 dan 84','gambarc' => '-','d' => '46 dan 94','gambard' => '-','jawaban' => '41 dan 84','gambar' => '-',]);
        Pengujian::create(['tipe' => 'numerik','soal' => 'Suatu seri: 100-4-90-7-80 seri selanjutnya adalah…','a' => '11','gambara' => '-','b' => '10','gambarb' => '-','c' => '9','gambarc' => '-','d' => '8','gambard' => '-','jawaban' => '10','gambar' => '-',]);
        Pengujian::create(['tipe' => 'numerik','soal' => 'Suatu seri: 9-5-1-2-10-6-2-3-11 -7- seri selanjutnya adalah…','a' => '3','gambara' => '-','b' => '4','gambarb' => '-','c' => '12','gambarc' => '-','d' => '7','gambard' => '-','jawaban' => '3','gambar' => '-',]);
        Pengujian::create(['tipe' => 'numerik','soal' => 'Suatu seri: 2-1-2-1-3-3-3-4-4- seri selanjutnya adalah…','a' => '3,4,7','gambara' => '-','b' => '4,5,7','gambarb' => '-','c' => '5,4,7','gambarc' => '-','d' => '6,4,5','gambard' => '-','jawaban' => '5,4,7','gambar' => '-',]);
        Pengujian::create(['tipe' => 'numerik','soal' => 'Suatu seri: 13-14-13-14-11-12-11-12-15-16-15-16-13 seri selanjutnya adalah…','a' => '11,15,13','gambara' => '-','b' => '12,16,14','gambarb' => '-','c' => '14,13,14','gambarc' => '-','d' => '14,15,13','gambard' => '-','jawaban' => '14,13,14','gambar' => '-',]);
        Pengujian::create(['tipe' => 'numerik','soal' => 'Suatu Deret b-m-n-d-o-p-… deret selanjutnya adalah…','a' => 'g','gambara' => '-','b' => 'q','gambarb' => '-','c' => 'r','gambarc' => '-','d' => 'f','gambard' => '-','jawaban' => 'r','gambar' => '-',]);
        Pengujian::create(['tipe' => 'numerik','soal' => 'Suatu Deret G-H-I-M-N-J-K-L-M-N... deret selanjutnya adalah…','a' => 'M-N','gambara' => '-','b' => 'N-M','gambarb' => '-','c' => 'O-P','gambarc' => '-','d' => 'P-O','gambard' => '-','jawaban' => 'M-N','gambar' => '-',]);
        Pengujian::create(['tipe' => 'skolastik','soal' => 'Usaha untuk menentang dominasi kekuasan adalah…','a' => 'makar','gambara' => '-','b' => 'membangkang','gambarb' => '-','c' => 'kritis','gambarc' => '-','d' => 'disosiasi','gambard' => '-','jawaban' => 'makar','gambar' => '-',]);
        Pengujian::create(['tipe' => 'skolastik','soal' => 'Antonim dari aktif adalah…','a' => 'dinamis','gambara' => '-','b' => 'statis','gambarb' => '-','c' => 'pasif','gambarc' => '-','d' => 'kreatif','gambard' => '-','jawaban' => 'pasif','gambar' => '-',]);
        Pengujian::create(['tipe' => 'skolastik','soal' => 'antonim dari canggih adalah…','a' => 'ruwet','gambara' => '-','b' => 'kompleks','gambarb' => '-','c' => 'berbelit-belit','gambarc' => '-','d' => 'sederhana','gambard' => '-','jawaban' => 'sederhana','gambar' => '-',]);
        Pengujian::create(['tipe' => 'skolastik','soal' => 'Mobil : bensin = …','a' => 'pelari:istirahat','gambara' => '-','b' => 'pelari:makanan','gambarb' => '-','c' => 'pelari:sepatu','gambarc' => '-','d' => 'pelari:lintasan','gambard' => '-','jawaban' => 'pelari:makanan','gambar' => '-',]);
        Pengujian::create(['tipe' => 'skolastik','soal' => 'penulis : komputer = …','a' => 'pemburu:senapan','gambara' => '-','b' => 'nelayan:ikan','gambarb' => '-','c' => 'penyanyi:kaser','gambarc' => '-','d' => 'guru:murid','gambard' => '-','jawaban' => 'pemburu:senapan','gambar' => '-',]);
        Pengujian::create(['tipe' => 'skolastik','soal' => 'Flash disk : data = …','a' => 'dompet:uang','gambara' => '-','b' => 'komputer:disker','gambarb' => '-','c' => 'waktu:arloji','gambarc' => '-','d' => 'rokok:asbak','gambard' => '-','jawaban' => 'dompet:uang','gambar' => '-',]);
        Pengujian::create(['tipe' => 'skolastik','soal' => 'Semua pegawai negeri berpakaian seragam. Sebagian pegawai negeri menggunakan dasi…','a' => 'sebagian pegawai negeri bersepatu','gambara' => '-','b' => 'sebagian pegawai negeri berseragam dan berdasi','gambarb' => '-','c' => 'sebagian pegawai negeri berseragam tapi tidak bersepatu','gambarc' => '-','d' => 'sebagian pegawai negeri berjas','gambard' => '-','jawaban' => 'sebagian pegawai negeri berseragam dan berdasi','gambar' => '-',]);
        Pengujian::create(['tipe' => 'skolastik','soal' => 'Semua dokter dapat membuat resep. Beberapa dokter ahli kandungan adalah penggemar lukisan…','a' => 'semua dokter adalah dokter kandungan','gambara' => '-','b' => 'semua dokter adalah penggemar lukisan','gambarb' => '-','c' => 'penggemar lukisan pasti dokter kandungan','gambarc' => '-','d' => 'beberapa dokter kandungan yang dapat membuat resep adalah penggemar lukisan','gambard' => '-','jawaban' => 'beberapa dokter kandungan yang dapat membuat resep adalah penggemar lukisan','gambar' => '-',]);
        Pengujian::create(['tipe' => 'skolastik','soal' => 'Semua perempuan suka bunga mawar. Semua bunga mawar berduri…','a' => 'tidak ada bunga mawar yang disukai perempuan yang tidak berdiri','gambara' => '-','b' => 'semua perempuan takut duri','gambarb' => '-','c' => 'tidak dapat ditarik kesimpulan','gambarc' => '-','d' => 'jika tidak berduri bunga mawar tidak disukai perempuan','gambard' => '-','jawaban' => 'tidak ada bunga mawar yang disukai perempuan yang tidak berdiri','gambar' => '-',]);
        Pengujian::create(['tipe' => 'skolastik','soal' => '1 , ... , 5, 9, 25, 27, 125, 81, ... , 243','a' => '1,325','gambara' => '-','b' => '3,625','gambarb' => '-','c' => '5,243','gambarc' => '-','d' => '7,343','gambard' => '-','jawaban' => '1,325','gambar' => '-',]);
        Pengujian::create(['tipe' => 'abstrak','soal' => 'Pilihlah gambar yang merupakan bangun yang sesuai dengan jaring-jaringnya','a' => 'A','gambara' => '1a.png','b' => 'B','gambarb' => '1b.png','c' => 'C','gambarc' => '1c.png','d' => 'D','gambard' => '1d.png','jawaban' => 'B','gambar' => '1.png',]);
        Pengujian::create(['tipe' => 'abstrak','soal' => 'Jika gambar dibawah berputar, manakh gambar yang identik dengan gambar di bawah','a' => 'A','gambara' => '2a.jpg','b' => 'B','gambarb' => '2b.jpg','c' => 'C','gambarc' => '2c.jpg','d' => 'D','gambard' => '2d.jpg','jawaban' => 'A','gambar' => '2.jpg',]);
        Pengujian::create(['tipe' => 'abstrak','soal' => 'Manakah gambar yang tepat untuk mengisi kotak pertanda tanya','a' => 'A','gambara' => '3a.png','b' => 'B','gambarb' => '3b.png','c' => 'C','gambarc' => '3c.png','d' => 'D','gambard' => '3d.png','jawaban' => 'D','gambar' => '3.png',]);
        Pengujian::create(['tipe' => 'abstrak','soal' => 'Manakah hasil uraian dari gambar berikut','a' => 'A','gambara' => '4a.jpg','b' => 'B','gambarb' => '4b.jpg','c' => 'C','gambarc' => '4c.jpg','d' => 'D','gambard' => '4d.jpg','jawaban' => 'C','gambar' => '4.jpg',]);
        Pengujian::create(['tipe' => 'abstrak','soal' => 'manakah hasil uraian dari gambar berikut','a' => 'A','gambara' => '5a.png','b' => 'B','gambarb' => '5b.png','c' => 'C','gambarc' => '5c.png','d' => 'D','gambard' => '5d.png','jawaban' => 'D','gambar' => '5.png',]);
        Pengujian::create(['tipe' => 'abstrak','soal' => 'Jika gambar dibawah diputar, manakah gambar yang identik dengan gambar dibawah','a' => 'A','gambara' => '6a.jpg','b' => 'B','gambarb' => '6b.jpg','c' => 'C','gambarc' => '6c.jpg','d' => 'D','gambard' => '6d.jpg','jawaban' => 'A','gambar' => '6.jpg',]);
        Pengujian::create(['tipe' => 'abstrak','soal' => 'manakah hasil uraian dari gambar berikut','a' => 'A','gambara' => '7a.jpg','b' => 'B','gambarb' => '7b.jpg','c' => 'C','gambarc' => '7c.jpg','d' => 'D','gambard' => '7d.jpg','jawaban' => 'A','gambar' => '7.jpg',]);
        Pengujian::create(['tipe' => 'abstrak','soal' => 'manakah hasil uraian dari gambar berikut','a' => 'A','gambara' => '8a.jpg','b' => 'B','gambarb' => '8b.jpg','c' => 'C','gambarc' => '8c.jpg','d' => 'D','gambard' => '8d.jpg','jawaban' => 'C','gambar' => '8.jpg',]);
        Pengujian::create(['tipe' => 'abstrak','soal' => 'jika gambar dibawah diputar, manakah gambar yang identik dengan gambar dibawah','a' => 'A','gambara' => '9a.jpg','b' => 'B','gambarb' => '9b.jpg','c' => 'C','gambarc' => '9c.jpg','d' => 'D','gambard' => '9d.jpg','jawaban' => 'B','gambar' => '9.jpg',]);
        Pengujian::create(['tipe' => 'abstrak','soal' => 'jika gambar dibawah diputar, manakah gambar yang identik dengan gambar dibawah','a' => 'A','gambara' => '10a.jpg','b' => 'B','gambarb' => '10b.jpg','c' => 'C','gambarc' => '10c.jpg','d' => 'D','gambard' => '10d.jpg','jawaban' => 'A','gambar' => '10.jpg',]);
        Pengujian::create(['tipe' => 'spasial','soal' => 'Tentukan Kelanjutan dari gambar berikut','a' => 'A','gambara' => 'spasial/1a.png','b' => 'B','gambarb' => 'spasial/1b.png','c' => 'C','gambarc' => 'spasial/1c.png','d' => 'D','gambard' => 'spasial/1d.png','jawaban' => 'B','gambar' => 'spasial/1.png',]);
        Pengujian::create(['tipe' => 'spasial','soal' => 'manakah kelanjutan gambar berikut','a' => 'A','gambara' => 'spasial/2a.png','b' => 'B','gambarb' => 'spasial/2b.png','c' => 'C','gambarc' => 'spasial/2c.png','d' => 'D','gambard' => 'spasial/2d.png','jawaban' => 'A','gambar' => 'spasial/2.png',]);
        Pengujian::create(['tipe' => 'spasial','soal' => 'pilihlah lanjutan dari gambar berikut','a' => 'A','gambara' => 'spasial/3a.png','b' => 'B','gambarb' => 'spasial/3b.png','c' => 'C','gambarc' => 'spasial/3c.png','d' => 'D','gambard' => 'spasial/3d.png','jawaban' => 'D','gambar' => 'spasial/3.png',]);
        Pengujian::create(['tipe' => 'spasial','soal' => 'pilihlah lanjutan dari gambar berikut','a' => 'A','gambara' => 'spasial/4a.jpg','b' => 'B','gambarb' => 'spasial/4b.jpg','c' => 'C','gambarc' => 'spasial/4c.jpg','d' => 'D','gambard' => 'spasial/4d.jpg','jawaban' => 'C','gambar' => 'spasial/4.jpg',]);
        Pengujian::create(['tipe' => 'spasial','soal' => 'lanjutan gambar berikut adalah','a' => 'A','gambara' => 'spasial/5a.jpg','b' => 'B','gambarb' => 'spasial/5b.jpg','c' => 'C','gambarc' => 'spasial/5c.jpg','d' => 'D','gambard' => 'spasial/5d.jpg','jawaban' => 'D','gambar' => 'spasial/5.jpg',]);
        Pengujian::create(['tipe' => 'spasial','soal' => 'pola gambar berikutnya adalah','a' => 'A','gambara' => 'spasial/6a.jpg','b' => 'B','gambarb' => 'spasial/6b.jpg','c' => 'C','gambarc' => 'spasial/6c.jpg','d' => 'D','gambard' => 'spasial/6d.jpg','jawaban' => 'A','gambar' => 'spasial/6.jpg',]);
        Pengujian::create(['tipe' => 'spasial','soal' => 'lanjutan gambar berikut','a' => 'A','gambara' => 'spasial/7a.jpg','b' => 'B','gambarb' => 'spasial/7b.jpg','c' => 'C','gambarc' => 'spasial/7c.jpg','d' => 'D','gambard' => 'spasial/7d.jpg','jawaban' => 'A','gambar' => 'spasial/7.jpg',]);
        Pengujian::create(['tipe' => 'spasial','soal' => 'lanjutkan gambar berikut','a' => 'A','gambara' => 'spasial/8a.jpg','b' => 'B','gambarb' => 'spasial/8b.jpg','c' => 'C','gambarc' => 'spasial/8c.jpg','d' => 'D','gambard' => 'spasial/8d.jpg','jawaban' => 'C','gambar' => 'spasial/8.jpg',]);
        Pengujian::create(['tipe' => 'spasial','soal' => 'pilih lanjutan gambar berikut','a' => 'A','gambara' => 'spasial/9a.jpg','b' => 'B','gambarb' => 'spasial/9b.jpg','c' => 'C','gambarc' => 'spasial/9c.jpg','d' => 'D','gambard' => 'spasial/9d.jpg','jawaban' => 'B','gambar' => 'spasial/9.jpg',]);
        Pengujian::create(['tipe' => 'spasial','soal' => 'lanjutan gambar berikut adalah','a' => 'A','gambara' => 'spasial/10a.jpg','b' => 'B','gambarb' => 'spasial/10b.jpg','c' => 'C','gambarc' => 'spasial/10c.jpg','d' => 'D','gambard' => 'spasial/10d.jpg','jawaban' => 'A','gambar' => 'spasial/10.jpg',]);
    }
}
